### PR TITLE
feat: various QOL improvements

### PR DESCRIPTION
**Pull request by rgracey**
Various QOL improvements:
- Allow ingress creation
- Make replica count configurable
  - Applying models `/models/apply` could have odd behaviour if multiple replicas are used (?)
- Allow `EmptyDir` usage for model storage (instead of a PVC)
- Allow multiple models to be downloaded via `initContainer`
- Make container resource requests and limits configurable ([issue](https://github.com/go-skynet/helm-charts/issues/5))
- Make `nodeSelector`, `tolerations` and `affinity` configurable ([issue](https://github.com/go-skynet/helm-charts/issues/5))
- Allow mounting of prompt templates via configmap

## Rendered Helm templates

<details>
  <summary>values.yaml</summary>
  
  ```yaml
  replicaCount: 1

  deployment:
    image: quay.io/go-skynet/local-ai:latest
    env:
      threads: 14
      contextSize: 512
      modelsPath: "/models"

  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  promptTemplates:
    ggml-gpt4all-j.bin.tmpl: |
      The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.
      ### Prompt:
      {{.Input}}
      ### Response:

  # Models to download at runtime
  models:
    # Whether to force download models even if they already exist
    forceDownload: false

    # The list of URLs to download models from
    # Note: the name of the file will be the name of the loaded model
    list:
      - url: "https://gpt4all.io/models/ggml-gpt4all-j.bin"
        basicAuth: base64EncodedCredentials

    # Persistent storage for models and prompt templates
    persistence:
      enabled: false
      size: 6Gi
      accessModes:
        - ReadWriteOnce

      annotations: {}

      # Optional
      storageClass: ~

  service:
    type: ClusterIP
    port: 80
    annotations: {}
    # If using an AWS load balancer, you'll need to override the default 60s load balancer idle timeout
    # service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "1200"

  ingress:
    enabled: true
    className: ""
    annotations:
      {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  nodeSelector: {}

  tolerations: []

  affinity: {}

  ```
</details>

<details>
  <summary>Rendered chart</summary>
  
  `$ helm template rgracey-patch-1 ./charts/local-ai`

  ```yaml
  ---
  # Source: local-ai/templates/configmap-prompt-templates.yaml
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: rgracey-patch-1-local-ai-prompt-templates
  data:
    ggml-gpt4all-j.bin.tmpl: |-
      The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.
      ### Prompt:
      {{.Input}}
      ### Response:
  ---
  # Source: local-ai/templates/service.yaml
  apiVersion: v1
  kind: Service
  metadata:
    name: rgracey-patch-1-local-ai
    namespace: "default"
    labels:
      helm.sh/chart: local-ai-2.0.0
      app.kubernetes.io/name: local-ai
      app.kubernetes.io/instance: "rgracey-patch-1"
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/version: "0.1.0"
  spec:
    selector:
      app.kubernetes.io/name: local-ai
    type: "ClusterIP"
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080
        name: http
  ---
  # Source: local-ai/templates/deployment.yaml
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: rgracey-patch-1-local-ai
    namespace: "default"
    labels:
      helm.sh/chart: local-ai-2.0.0
      app.kubernetes.io/name: local-ai
      app.kubernetes.io/instance: "rgracey-patch-1"
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/version: "0.1.0"
  spec:
    selector:
      matchLabels:
        app.kubernetes.io/name: local-ai
        app.kubernetes.io/instance: rgracey-patch-1
    replicas: 1
    template:
      metadata:
        name: rgracey-patch-1-local-ai
        labels:
          app.kubernetes.io/name: local-ai
          app.kubernetes.io/instance: rgracey-patch-1
        annotations:
          checksum/config-prompt-templates: 78b77b2019bcdf64329ecd9577274dca2b1c710217b1e9b72c57fe35bdfd0127
      spec:
        initContainers:
          - name: prompt-templates
            image: busybox
            command: ["/bin/sh", "-c"]
            args:
              - |
                cp -fL /prompt-templates/* /models
            volumeMounts:
              - mountPath: /prompt-templates
                name: prompt-templates
              - mountPath: /models
                name: models
          - name: download-model
            image: busybox
            command: ["/bin/sh", "-c"]
            args:
              - |
                MODEL_DIR=/models
                FORCE_DOWNLOAD=false
                URLS="https://gpt4all.io/models/ggml-gpt4all-j.bin base64EncodedCredentials,"

                mkdir -p "$MODEL_DIR"

                # Split urls on commas
                echo "$URLS" | awk -F, '{for (i=1; i<=NF; i++) print $i}' | while read -r line; do
                    url=$(echo "$line" | awk '{print $1}')
                    auth=$(echo "$line" | awk '{print $2}')

                    if [ -n "$url" ]; then
                        filename=$(basename "$url")

                        if [ "$FORCE_DOWNLOAD" = false ] && [ -f "$MODEL_DIR/$filename" ]; then
                            echo "File $filename already exists. Skipping download."
                            continue
                        fi

                        rm -f "$MODEL_DIR/$filename"

                        echo "Downloading $filename"

                        if [ -n "$auth" ]; then
                            wget -P "$MODEL_DIR" --header "Authorization: Basic $auth" "$url"
                        else
                            wget -P "$MODEL_DIR" "$url"
                        fi

                        if [ "$?" -ne 0 ]; then
                            echo "Download failed."
                        else
                            echo "Download completed."
                        fi
                    fi
                done
            volumeMounts:
            - mountPath: /models
              name: models
        containers:
          - name: rgracey-patch-1-local-ai
            image: quay.io/go-skynet/local-ai:latest
            resources:
              limits:
                cpu: 250m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
            env:
            - name: THREADS
              value: "14"
            - name: CONTEXT_SIZE
              value: "512"
            - name: MODELS_PATH
              value: /models
            volumeMounts:
            - mountPath: /models
              name: models
        volumes:
        - name: models
          emptyDir: {}
        - name: prompt-templates
          configMap:
            name: rgracey-patch-1-local-ai-prompt-templates
  ---
  # Source: local-ai/templates/ingress.yaml
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: rgracey-patch-1-local-ai
    labels:
      helm.sh/chart: local-ai-2.0.0
      app.kubernetes.io/name: local-ai
      app.kubernetes.io/instance: "rgracey-patch-1"
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/version: "0.1.0"
  spec:
    rules:
      - host: "chart-example.local"
        http:
          paths:
            - path: /
              pathType: ImplementationSpecific
              backend:
                service:
                  name: rgracey-patch-1-local-ai
                  port:
                    number: 80
  ```
</details>

### CODE REVIEW

**Comment by rgracey** [comment]
@TylerGillson @mudler I can't add any reviewers, but let me know if anything needs to be changed.

**Review by TylerGillson — CHANGES_REQUESTED** [review]
Thanks @rgracey! Everything about this looks great, except for the removal of basic auth support for downloading the models. I agree that what was there was hacky.. so definitely open to suggestions for improvement, support for other auth methods, etc. But let's not just remove it outright please.

**Comment by rgracey** [comment]
> Thanks @rgracey! Everything about this looks great, except for the removal of basic auth support for downloading the models. I agree that what was there was hacky.. so definitely open to suggestions for improvement, support for other auth methods, etc. But let's not just remove it outright please.

@TylerGillson Oops 🤦 basic auth has been added back in 🚀

**Review by mudler — APPROVED** [review]
looks good, thanks @rgracey !

**Comment by mudler** [comment]
@rgracey are you also updating the docs in LocalAI?  :sweat_smile:

**Pull request merged**
